### ISSUE TITLE
Politeia Proposal TODO

### ISSUE THREAD

**Issue by RussGlover** [RussGlover/decred-bug-bounty-proposal#8]
- [ ] Add Glossary #7

- [ ] Choose Bug bounty platform #4

- [ ] Define Internal response Procedure #2

- [ ] Define security.md content #6

- [ ] Develop plan for phase 1 #5

- [ ] Complete budget #1

- [ ] Choose Politeia proposal structure and content #3

- [ ] Post to Politeia
